#!/usr/bin/env python3
"""html_docs_to_txt.py -- Convert an HTML documentation site into plain-text
.txt files: one .txt per documentation section, containing the full text of
all its child pages, with site chrome / boilerplate stripped.

Stdlib only (no pip dependencies).

Modes:
  auto     detect the generator automatically (default)
  doxygen  parse navtreedata.js NAVTREE for the exact page/section tree
  crawl    BFS-crawl same-host .html links (MkDocs, Docusaurus, plain HTML)

Usage:
  python3 html_docs_to_txt.py URL [options]

Options:
  --out DIR      output directory (default: ./docs_txt/<site-name>)
  --mode M       auto | doxygen | crawl          (default: auto)
  --flat         write ONE combined .txt instead of one per section
  --per-page     write one .txt per page instead of per section
  --max-pages N  crawl limit in crawl mode       (default: 200)
  --delay S      politeness delay between fetches, seconds (default: 0.2)
  --strip RE     extra boilerplate regex, applied per line (repeatable)
  --ua STR       User-Agent header                (default: Mozilla/5.0 ...)
  --quiet        suppress progress output
"""
import argparse
import re
import sys
import time
import urllib.parse
import urllib.request
from html.parser import HTMLParser
from pathlib import Path

CONTENT_IDS = {"doc-content", "content", "main-content", "documentation",
               "docs-content", "wiki-content", "markdown-section"}
CONTENT_CLASSES = {"markdown-section", "theme-doc-markdown", "md-content",
                   "document", "contents", "doc"}
BOILERPLATE = [
    r"^(Loading|Searching|No Matches|Search)[. …]*$",
    r"^Generated by [\d.]+$",
    r"^Click to (search|show|hide).*$",
]

# ---------------------------------------------------------------- HTTP layer

def make_fetcher(ua, delay):
    cache = {}

    def fetch(url):
        if url not in cache:
            for attempt in range(3):
                try:
                    req = urllib.request.Request(url, headers={"User-Agent": ua})
                    with urllib.request.urlopen(req, timeout=30) as r:
                        cache[url] = r.read().decode("utf-8", "replace")
                    break
                except Exception as e:
                    if attempt == 2:
                        sys.stderr.write(f"WARN: fetch failed {url}: {e}\n")
                        cache[url] = ""
                    else:
                        time.sleep(delay + attempt)
            time.sleep(delay)
        return cache[url]

    return fetch


def sanitize(name):
    name = re.sub(r"[^\w\s-]", "", name).strip()
    return re.sub(r"[\s-]+", "_", name)[:60] or "page"


# ---------------------------------------------------------------- navigation

def navtree_sections(fetch, base):
    """Doxygen: parse var NAVTREE in navtreedata.js.

    Returns [(section_title, [page_url, ...]), ...]. Top-level entries are
    sections; unique .html descendants are child pages. Entries whose url is
    an anchor (page.html#frag) are skipped: their text already lives inside
    the parent page's HTML.
    """
    js = fetch(urllib.parse.urljoin(base, "navtreedata.js"))
    if not js or "var NAVTREE" not in js:
        return []
    start = js.index("var NAVTREE")
    end = re.search(r"\];", js[start:])
    body = js[start:start + (end.end() if end else len(js) - start)]
    toks = re.findall(r'"(?:[^"\\]|\\.)*"|\[|\]', body)

    def parse(i):
        out = []
        while i < len(toks):
            t = toks[i]
            if t == "[":
                sub, i = parse(i + 1)
                out.append(sub)
            elif t == "]":
                return out, i + 1
            else:
                out.append(t.strip('"'))
                i += 1
        return out, i

    tree, _ = parse(0)
    sections = []

    def urls(node):
        got = []
        for ch in node:
            if isinstance(ch, list):
                # recurse into every list child; a bare container list has a
                # non-string second element and must not be skipped
                if len(ch) >= 2 and isinstance(ch[1], str) and ch[1].endswith(".html"):
                    got.append(ch[1])
                got.extend(urls(ch))
        return got

    # unwrap wrapper lists: NAVTREE = [ [ "Site", "index.html", [sec, ...] ] ]
    # descend through single-entry wrappers to reach the root entry.
    node = tree
    while isinstance(node, list) and len(node) == 1 and isinstance(node[0], list):
        node = node[0]
    # node is now the root entry; its list element holds the top-level sections
    tops = [x for x in node if isinstance(x, list)] if isinstance(node, list) else []
    if len(tops) == 1 and tops[0] and all(isinstance(x, list) for x in tops[0]):
        tops = tops[0]  # unwrap [site, url, [section, ...]] -> [section, ...]
    for top in tops:
        if len(top) >= 2 and isinstance(top[0], str) and isinstance(top[1], str):
            pages = []
            if top[1].endswith(".html"):
                pages.append(top[1])
            pages.extend(urls(top))
            seen, uniq = set(), []
            for p in pages:
                if p not in seen:
                    seen.add(p)
                    uniq.append(p)
            if uniq:
                sections.append((top[0], uniq))
    return sections


def crawl_pages(fetch, base, max_pages):
    """Generic: BFS same-host .html links. Returns ordered list of URLs."""
    start = urllib.parse.urlparse(base)
    seen, order, queue = set(), [], [base.rstrip("/") + "/"]
    while queue and len(order) < max_pages:
        url = queue.pop(0)
        if url in seen:
            continue
        seen.add(url)
        html = fetch(url)
        if not html:
            continue
        order.append(url)
        for m in re.finditer(r'href="([^"#]+\.html?)"', html):
            u = urllib.parse.urljoin(url, m.group(1))
            p = urllib.parse.urlparse(u)
            if p.netloc == start.netloc and u not in seen:
                queue.append(u)
    return order


# ---------------------------------------------------------------- extraction

class Extractor(HTMLParser):
    """Collect plain text from the main content container; fall back to
    <body> minus nav/header/footer/aside/script/style."""
    SKIP = {"script", "style", "nav", "header", "footer", "aside",
            "noscript", "svg", "form", "button"}
    BLOCK = {"p", "div", "h1", "h2", "h3", "h4", "h5", "h6", "li", "tr",
             "dt", "dd", "pre", "table", "blockquote", "section", "br"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.skip = 0
        self.body_buf = []
        self.stack = []      # [tag, buf] for open content containers
        self.candidates = []

    def _is_content(self, tag, attrs):
        d = dict(attrs)
        if tag in ("main", "article") or d.get("id") in CONTENT_IDS:
            return True
        if d.get("role") == "main":
            return True
        return bool(set((d.get("class") or "").split()) & CONTENT_CLASSES)

    def handle_starttag(self, tag, attrs):
        if tag in self.SKIP:
            self.skip += 1
        if tag in self.BLOCK:
            self._emit("\n")
        if tag in ("td", "th"):
            self._emit(" | ")
        if not self.stack and self._is_content(tag, attrs):
            self.stack.append([tag, []])
        elif self.stack and tag == self.stack[-1][0]:
            self.stack.append([tag, []])

    def handle_endtag(self, tag):
        if tag in self.SKIP and self.skip:
            self.skip -= 1
        if self.stack and tag == self.stack[-1][0]:
            _, buf = self.stack.pop()
            self.candidates.append("".join(buf))
        if tag in self.BLOCK:
            self._emit("\n")

    def handle_data(self, data):
        self._emit(data)

    def _emit(self, text):
        if self.skip:
            return
        for c in self.stack:
            c[1].append(text)
        if not self.stack:
            self.body_buf.append(text)


def to_text(html, extra_strip=()):
    """HTML -> cleaned plain text. NB: non-breaking spaces are normalized
    FIRST -- they otherwise defeat exact-match boilerplate stripping."""
    p = Extractor()
    try:
        p.feed(html)
    except Exception:
        pass
    raw = max(p.candidates, key=len) if p.candidates else "".join(p.body_buf)
    raw = raw.replace("\xa0", " ").replace("‌", "").replace("‍", "")
    pats = [re.compile(x) for x in BOILERPLATE] + \
           [re.compile(x) for x in extra_strip]
    lines = [ln for ln in raw.split("\n")
             if not any(pat.match(ln.strip()) for pat in pats)]
    txt = "\n".join(lines)
    txt = re.sub(r"[ \t]+", " ", txt)
    txt = re.sub(r"\n\s*\n+", "\n\n", txt)
    return txt.strip() + "\n"


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description="HTML docs site -> .txt files")
    ap.add_argument("url")
    ap.add_argument("--out")
    ap.add_argument("--mode", choices=["auto", "doxygen", "crawl"], default="auto")
    ap.add_argument("--flat", action="store_true")
    ap.add_argument("--per-page", action="store_true")
    ap.add_argument("--max-pages", type=int, default=200)
    ap.add_argument("--delay", type=float, default=0.2)
    ap.add_argument("--strip", action="append", default=[])
    ap.add_argument("--index-min", type=int, default=1500,
                    help="pages with text shorter than this are treated as "
                         "index pages and expanded with their child pages")
    ap.add_argument("--ua", default="Mozilla/5.0 (X11; Linux x86_64) docs-to-txt/1.0")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args()

    base = a.url.rstrip("/") + "/"
    fetch = make_fetcher(a.ua, a.delay)
    say = (lambda *x: None) if a.quiet else print

    sections = []
    if a.mode in ("auto", "doxygen"):
        sections = navtree_sections(fetch, base)
    if sections and a.mode != "crawl":
        say(f"[mode] doxygen navtree: {len(sections)} sections")
    else:
        pages = crawl_pages(fetch, base, a.max_pages)
        say(f"[mode] crawl: {len(pages)} pages")
        groups = {}
        for u in pages:
            parts = [x for x in urllib.parse.urlparse(u).path.split("/") if x]
            key = parts[0] if len(parts) > 1 else "root"
            groups.setdefault(key, []).append(u)
        order = ["root"] + [k for k in groups if k != "root"]
        sections = [(k, groups[k]) for k in order if k in groups]

    host = urllib.parse.urlparse(base).netloc.replace(".", "_")
    out = Path(a.out) if a.out else Path("docs_txt") / host
    out.mkdir(parents=True, exist_ok=True)

    # ---- fetch pages, expanding short "index" pages (e.g. Doxygen group
    # listings such as Functions / Data types) with their child pages -------
    EXCLUDE_STEMS = ("index", "pages", "modules", "files", "annotated",
                     "globals", "dirs", "dir_", "namespaces", "search",
                     "navtree", "doxygen", "menudata", "cookie", "resize",
                     "dynsections", "tabs", "classe", "function", "struct",
                     "typedef", "define", "enum", "union")
    INDEX_MIN_CHARS = a.index_min   # shorter page text => index page, expand

    def children_of(url):
        out = []
        for m in re.finditer(r'href="([^"#]+\.html?)"', fetch(url)):
            child = urllib.parse.urljoin(url, m.group(1))
            cu = urllib.parse.urlparse(child)
            stem = cu.path.rsplit("/", 1)[-1].rsplit(".", 1)[0]
            if cu.netloc != urllib.parse.urlparse(base).netloc:
                continue
            if stem.startswith(EXCLUDE_STEMS):
                continue
            out.append(child)
        return out

    section_pages = []   # [(title, [(url, text), ...]), ...]
    included = set()

    def get_page(url):
        txt = to_text(fetch(url), a.strip)
        return (url, txt)

    for title, pages in sections:
        entries = []
        for p in pages:
            url = urllib.parse.urljoin(base, p)
            if url in included:
                continue
            included.add(url)
            say(f"  fetching {url}")
            entries.append(get_page(url))
            if len(entries[-1][1]) < INDEX_MIN_CHARS:
                for child in children_of(url):
                    if child not in included:
                        included.add(child)
                        say(f"  fetching {child} (index child)")
                        entries.append(get_page(child))
        section_pages.append((title, entries))
    all_pages = [e for _, es in section_pages for e in es]

    def header(title, url):
        return "=" * 78 + f"\n{title}  ({url})\n" + "=" * 78 + "\n"

    if a.flat:
        (out / "ALL_DOCS.txt").write_text(
            "\n".join(header(u, u) + t for u, t in all_pages), encoding="utf-8")
        say(f"wrote {out}/ALL_DOCS.txt")
    elif a.per_page:
        for u, t in all_pages:
            name = Path(urllib.parse.urlparse(u).path).stem or "index"
            (out / f"{sanitize(name)}.txt").write_text(
                header(t.split("\n", 1)[0], u) + t, encoding="utf-8")
        say(f"wrote {len(all_pages)} per-page .txt files to {out}")
    else:
        for idx, (title, entries) in enumerate(section_pages, 1):
            fname = f"{idx:02d}_{sanitize(title)}.txt"
            (out / fname).write_text(
                "\n".join(header(title, u) + t for u, t in entries),
                encoding="utf-8")
            say(f"wrote {out}/{fname} ({len(entries)} pages)")
    say(f"total: {len(all_pages)} pages -> {out}")


if __name__ == "__main__":
    main()
