blank_issues_enabled: false
contact_links:
  - name: "🛡 Report a security vulnerability"
    about: Please refer to the SECURITY.md file for instructions.
    url: ./../../SECURITY.md
  - name: "🛱 Request support"
    about: You can reach out to the ST Community.
    url: https://community.st.com/s/topiccatalog
